[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.partitions = huge_app.csv
upload_port = COM6
monitor_port = COM6
upload_flags =
    --before=no_reset
    --after=no_reset
    --baud
    115200